/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    Dialog: typeof import('./inertia/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./inertia/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./inertia/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./inertia/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./inertia/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./inertia/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./inertia/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./inertia/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./inertia/components/ui/dialog/DialogTrigger.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    MdxContent: typeof import('./inertia/components/MdxContent.vue')['default']
    Toast: typeof import('./inertia/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./inertia/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./inertia/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./inertia/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./inertia/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./inertia/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./inertia/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./inertia/components/ui/toast/ToastViewport.vue')['default']
  }
}
